version: '3'
services:
  rust-terminal:
    build:
      context: ./remote_terminal
      dockerfile: Dockerfile
    ports:
      - 8082:8082
    volumes:
      - ./remote_terminal:/home/app/remote_terminal
    networks:
      - internal-network

   remote-server:
    build:
      context: ./remote_server
      dockerfile: Dockerfile
    ports:
      - 8083:8083
    volumes:
      - ./remote_server:/home/app/remote_server
    networks:
      - internal-network

networks:
  internal-network:
