# Temporary stage to copy lib directory
FROM gcc:4.9 as libstage
COPY ./lib /usr/src/temp_lib

FROM gcc:4.9
RUN ["mkdir", "-p", "/usr/src/client_shell/lib"]
#RUN ["mkdir", "-p", "/usr/src/client_shell_build/lib"]
COPY --from=libstage /usr/src/temp_lib /usr/src/client_shell/lib
#_build/lib
COPY ./c_remote_client /usr/src/client_shell
#_build
WORKDIR /usr/src/client_shell
#_build
RUN ls -lsa
RUN ls -lsa lib
RUN ["make", "all"]
RUN ls -lsa
CMD ["bash"]
#CMD ["cp", "/usr/src/client_shell_build/", "/usr/src/client_shell/", "&&", "cd", "/usr/src/client_shell/", "&&", "./client_shell"]