# Temporary stage to copy lib directory
FROM gcc:4.9 as libstage
COPY ./lib /usr/src/temp_lib

FROM gcc:4.9
RUN ["mkdir", "-p", "/usr/src/client_shell/lib"]
COPY --from=libstage /usr/src/temp_lib /usr/src/client_shell/lib
COPY ./c_remote_client /usr/src/client_shell
WORKDIR /usr/src/client_shell
RUN ls -lsa
RUN ls -lsa lib
RUN ["make", "all"]
CMD ["bash"]
# CMD ["./client_shell"]